const { SHIP_TYPES } = require('./SHIPS');

const DEFAULT = {
  SHIP_LIST: [
    SHIP_TYPES.DESTROYER.NAME,
    SHIP_TYPES.SUBMARINE.NAME,
    SHIP_TYPES.CRUISER.NAME,
    SHIP_TYPES.BATTLESHIP.NAME,
    SHIP_TYPES.AIRCRAFT_CARRIER.NAME
  ]
}

module.exports = {
  DEFAULT
}